Added Bootstrap, favicon, header image (with copyright notice in foot…
EddyLuten/fuckmy.party pull request #2
Opened 2016-11-15 06:21 UTC by woodyaz

I did some stuff.

* Added bootstrap
*  Favicon!
*  Stats is now an inline un-ordered list.
*  Header image?

Let me know what y'all think!

2016-11-15 06:59 UTC, EddyLuten commented
Yes, I like. :feelsgood: But if you don't mind I'm popping in a few comments here and there.

2016-11-15 07:22 UTC, EddyLuten requested changes
Right direction, but a few things that need to be addressed before merging.

2016-11-15 07:22 UTC, EddyLuten commented on css/style.css
> +    background-image: url("../images/party.jpg");
I love this image (and favicon), it really shows the kind of party I had in mind when making this. However, the image is licensed as CC BY-SA 4.0 and I'm not 100% sure if that's compatible with this site's MIT licensing.

Also, I can't comment on binary files, but did you make the favicon yourself or did you get it somewhere? If the former, also need to check if the licenses are compatible just to cover ass.

As far as style, do you think the image could be faded a bit or maybe some kind of gradient overlay? It's a bit hard to read the header text on top of it.

Lastly, and sorry for the waterfall of comments on this one thing, do you think it's possible to reduce the size of the image? It's 3.2MB and a bit on the sluggish side to load, even running locally.

![network-load](https://cloud.githubusercontent.com/assets/1082806/20296523/3e4d5aee-aac0-11e6-8b9d-949b33ebc94d.png)

2016-11-15 07:22 UTC, EddyLuten commented on index.html
> +    <footer class="text-center">
Do you think the font size for the footer could be a bit smaller to differentiate it from the main content?

2016-11-15 07:22 UTC, EddyLuten commented on index.html
> -    }
Consider adding the .error class back in since it provides feedback when a field is left empty or invalid.

2016-11-15 09:01 UTC, woodyaz commented on css/style.css
> +    background-image: url("../images/party.jpg");
Regarding the header image, that's a good question...  Let me do some digging and/or find something else.

The middle finger source is public domain.  https://commons.wikimedia.org/wiki/File:The_middle_finger.svg; I just made an icon from it.

I'll make the header more readable,, and I'll resize the header imagine, assuming there are no legal issues.

2016-11-21 02:07 UTC, woodyaz commented on index.html
> -    }
The latest commit adds the 'has-error' class added from Bootstrap, which "reds" it all out.

2016-11-21 02:09 UTC, woodyaz commented
I forgot to add, I changed the stats randomizer to make ti play better with bootstrap, but if there are any issues, I can change it back.

2016-11-29 21:40 UTC, EddyLuten approved these changes
👍 merging!

2016-11-29 21:40 UTC, merged